#
logging:
  config: classpath:logback-spring.xml
#
spring:
  main:
    banner-mode: "OFF"
  application:
    name: video-task
  datasource:
    tiles:
      actype: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/video
      username: root
      password: root
  profiles:
    active: @env@
#
mybatis:
  check-config-location: false
  config-location: classpath:mybatis-cfg.xml
  mapper-locations:
    - com/xdf/ucan/remix/video/task/dao/**/**.xml
  type-aliases-package: com.xdf.ucan.remix.video.task.dao
####################
#
####################
